import sys
import os
import pandas as pd
import getpass
import datetime


# Read the .xlsx file
def readStringsFromExcelAndCreateLocalizationFile():
	dirName = os.getcwd()
	data = pd.read_excel(dirName + "/localization.xlsx", header=None)
	createLocalizableFiles(data)

# Create Localizable strings file
def createLocalizableFiles(fileContent):
	for column in fileContent:
		if column == 0:
			continue;
		langName = fileContent[column][0]
		dirName = os.getcwd()
		iOSFilePath = (dirName + "/Localization" + "/" + langName + ".lproj/")
		iOSFile = iOSFilePath + "Localizable.strings"
		if langName == 'en':
			androidFilePath = (dirName + "/res" + "/values" + "/")
		else :
			androidFilePath = (dirName + "/res" + "/values-" + langName + "/")
		androidFile = androidFilePath + "strings.xml"
		if not os.path.exists(iOSFilePath):
        		os.makedirs(iOSFilePath)
        		if not os.path.exists(androidFilePath):
            			os.makedirs(androidFilePath)

		writeLocalizedStringsToFile(iOSFile, androidFile, fileContent, column)

# Write Localizable strings into files
def writeLocalizedStringsToFile(iOSFile, androidFile, fileContent, columnIndex):
	iOSStringFile = writeHeaderInfoToIOSFile(iOSFile)
	writeIOSStringsToFile(iOSStringFile,fileContent, columnIndex)
	androidStringFile = writeHeaderInfoToAndroidFile(androidFile)
	writeAndroidStringsToXml(androidStringFile, fileContent, columnIndex)

# Write Header info in iOS file
def writeHeaderInfoToIOSFile(file):
	stringFile = open(file, "w+")
	today = datetime.date.today()
	now = datetime.datetime.now()
	stringFile.write("// © Rohit Ranjan Pandey., {0}. All rights reserved.\n\n".format(today.year))
	stringFile.write("// +-------------------------------------------------------------------+ \n \n")
	stringFile.write("// This file is auto-generated from localization excel file. \n")
	stringFile.write("// Do not edit this file directly. \n")
	stringFile.write("// Created by: {0} \n".format(getpass.getuser()))
	stringFile.write("// Date Time: {0} \n".format(now.strftime("%Y-%m-%d %H:%M:%S")))
	stringFile.write("\n \n")
	return stringFile

# Write Header info in Android file
def writeHeaderInfoToAndroidFile(file):
	stringFile = open(file, "w+")
	today = datetime.date.today()
	now = datetime.datetime.now()
	stringFile.write("<!-- © Rohit Ranjan Pandey., {0}. All rights reserved.--> \n\n".format(today.year))
	stringFile.write("<!-- ####################################################################### --> \n")
	stringFile.write("<!--  This file is auto-generated from localization excel file. -->  \n")
	stringFile.write("<!--  Do not edit this file directly. --> \n")
	stringFile.write("<!-- Created by: {0} --> \n".format(getpass.getuser()))
	stringFile.write("<!-- Date Time: {0} --> \n".format(now.strftime("%Y-%m-%d %H:%M:%S")))
	stringFile.write("<!-- ####################################################################### -->")
	stringFile.write("\n \n")
	return stringFile


# Write strings into iOS .strings file
def writeIOSStringsToFile(file, fileContent, columnIndex):
	fileContent = '"' + fileContent.astype(str) + '"'
	for row in fileContent.index: 
		try:
			contentToWrite = (fileContent[0][row] + " = "+  fileContent[columnIndex][row])
			file.write(contentToWrite)
			file.write("\n")
		except IndexError:
			print ("Error in iOS sheet" + "IndexError")

# Write strings into Android .xml file
def writeAndroidStringsToXml(file, fileContent, columnIndex):
	file.write("<resources>")
	file.write("\n")
	for row in fileContent.index: 
		try:
			key = '"' + fileContent[0][row] + '"'
			value = fileContent[columnIndex][row]
			contentToWrite = "    <string name={0}>".format(key) + value + "</string>"
			file.write(contentToWrite)
			file.write("\n")
		except IndexError:
			print ("Error in Android sheet" + "IndexError")

	file.write("</resources>")

def main():
	readStringsFromExcelAndCreateLocalizationFile()

main()




